---
title: "p8105_hw6_kp3127"
output: html_document
date: "2025-12-02"
---
```{r setup, echo=FALSE}
library(tidyverse)
library(broom)
library(ggplot2)
library(rvest)
library(patchwork)
library(purrr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
set.seed(1)
```

# Problem 1
Cleaning the dataset 
```{r}
homi_df=read.csv("./homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    city_state = str_c(city, ", ", state),
    victim_age = as.numeric(victim_age),
    solved = if_else(disposition == "Open/No arrest", 0, 1),
  ) %>% 
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", 
                       "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("White", "Black"),
    !is.na(victim_age),
    !is.na(victim_sex),
    !is.na(solved)
  ) %>% 
  mutate(
    victim_race = fct_relevel(victim_race, "White"),
    victim_sex  = fct_relevel(victim_sex, "Female")
  )  
```

Logistic regression for Baltimore
```{r}
baltimore_df = homi_df %>% 
  filter(city_state == "Baltimore, MD")

baltimore_fit = 
  glm(
    solved~victim_age + victim_sex + victim_race,
    data   = baltimore_df,
    family = binomial()
  )

baltimore_or =
  baltimore_fit %>% 
  tidy(conf.int = TRUE, exponentiate = TRUE) %>% 
  filter(term == "victim_sexMale") %>% 
  select(term, estimate, conf.low, conf.high)

baltimore_or |> 
  knitr::kable(digits = 3)
```

Logistic regression for all
```{r}
city_or_df <- 
  homi_df |>
  group_by(city_state) |>
  nest() |>
  mutate(
    model = map(
      data,
      ~ .x |>
        mutate(
          victim_sex  = fct_relevel(victim_sex, "Female"),
          victim_race = fct_relevel(victim_race, "White")
        ) |>
        glm(
          solved ~ victim_age + victim_sex + victim_race,
          data   = _,
          family = binomial()
        )
    ),
    results = map(
      model,
      ~ tidy(.x, conf.int = TRUE, exponentiate = TRUE)
    )
  ) |>
  unnest(results) |>
  filter(term == "victim_sexMale") |>
  select(city_state,estimate,conf.low,conf.high) |>
  arrange(city_state)
```

Plots
```{r}
ggplot(city_or_df, aes(x = city_state, 
                            y = estimate)) +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high)) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  coord_flip() +
  labs(
    x = "City",
    y = "Adjusted OR (Male vs Female)",
    title = "Adjusted odds ratio of homicide being solved,\ncomparing male vs female victims by city"
  ) +
  theme_minimal() 
```

